- hosts: 192.168.221.124
  become: yes
  vars:
    archivo: "{{pathArchivo}}"
  tasks:
    - name: instalo apache
      apt:
        name: apache2
        state: latest
    - name:  copio archivo
      copy:
        src: "{{archivo}}"
        dest: /var/www/html/hola.php 
